version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/car-rental-front
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
